// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PowertPlant.WebApi.Entity;

#nullable disable

namespace PowertPlant.WebApi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220119205114_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PowertPlant.WebApi.Entity.ElectroMeter", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("webid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("ElectroMeters");
                });

            modelBuilder.Entity("PowertPlant.WebApi.Entity.TimedValue", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("value")
                        .HasColumnType("int");

                    b.Property<Guid>("webid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("TimedValues");
                });
#pragma warning restore 612, 618
        }
    }
}
